# Conclusion

In order to evaluate the performance of Hermès during pandemic, we analyzed the revenue by different factors, financial statement, key figure and stock price.

By comparing the revenue geographically of Hermès in 2019 with that in 2020, we can get the conclusion that the Covid-19 have been negatively influenced revenue from all area except Asian at the first half year and recovered gradually at the last quarter year. The revenue from Asian has not been influenced at all and increase.  The main consumer from Asian might be from China by looking at the stare global distribution where there are highest stores’ density in China. However, the growth of revenue in Asian does not make up the loss in other regions. In 2020 year, Hermès decreases 500 million EU compared with revenue in 2019. By saving in Selling, marketing and administrative expenses, they diminish this loss to 300 millions EU, final profit from 1500 millions EU to 1300 millions EU. However, those negative influence on revenues does not affect consumer’s passion to Hermès’s leather product which takes nearly half of revenue of Hermès. 

Although the Revenue and Recurring operating decrease and back to 2018 level, the workforce of company is keeping same increase rate which represent the growth of Hermès company is not affected by Covid-19. Also, we can check that the total asset of Hermès increased as well, and the stockholder equality increase as well. And the stockholder also shows large market confidence on Hermès. During pandemic period, although the stock price of Hermès fluctuates with market, it still shows relative static compared with other luxury stock.

From overall, although Hermès’s revenue has been impacted by Covid-19, their customers' loyalty shows great confidence in the future. The group remains highly committed and active, and gradually adapts measures to those taken by health and public authorities.